### PR TITLE
Style projects

### PR DESCRIPTION
**Pull request by JMurphyWeb**
# ready

- [x] Add styling to project details view
- [x] add form divider
- [x] add data component

#51

### CODE REVIEW

**Comment by jackcarlisle** [comment]
@JMurphyWeb merge conflicts in `app.css` but happy to merge after they're fixed!

**Comment by JMurphyWeb** [comment]
@jackcarlisle sorry i forgot to push up yesterday. don't merge just yet.

**Comment by jackcarlisle** [comment]
@JMurphyWeb let me know when it's ready to review

**Comment by JMurphyWeb** [comment]
@jackcarlisle this is now ready. A few small changes since last review..

**Comment by jackcarlisle** [comment]
@JMurphyWeb slightly unrelated review but when I started the project it gave be a few warnings about unused variables in the password controller. Do you want to take a look at that? I can fix in my next PR if you wanna get this merged

**Comment by JMurphyWeb** [comment]
happy to look into it

**Comment by JMurphyWeb** [comment]
@jackcarlisle it is already fixed actually

**Comment by jackcarlisle** [comment]
merging 🔥

**Pull request merged**
